name: Setup Base Dependencies
description: Setup base dependencies
inputs:
  platform:
    required: true
    description: Target platform.
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Setup SCons 4.4
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons==4.4.0
        scons --version

    - name: Setup Android Dependencies
      if: inputs.platform == 'android'
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23c
        link-to-sdk: true

    - name: Setup Windows Dependencies
      if: inputs.platform == 'windows'
      shell: sh
      run: |
          sudo apt-get install mingw-w64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

    - name: Setup Web Dependencies
      if: inputs.platform == 'web'
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.64
        no-cache: true

    - name: Verify Emscripten setup
      if: inputs.platform == 'web'
      shell: bash
      run: |
        emcc -v
