# Pasture3D Water Bodies — Phase 1 exit gate (spec §11, PASTURE3D_WATER_BODIES_SPEC.md).
#
# Phase 1 adds Pasture3DWaveProfile and Pool3DManager, moves the clock and the sun
# onto the manager, introduces the (base material, profile) material cache, and
# promotes _water_domain_origin to an instance uniform.
#
# Gate criteria, from the spec's phase table:
#   A. CPU/GPU parity <= 1 cm for TWO DIFFERENT PROFILES in one scene
#   B. instance origin -- two meshes 5 km apart on one material are both correct;
#      the control is the old shared-uniform behaviour, which must fail
#   C. ten pools on one profile cost ONE material and ONE upload
#   D. the manager owns the clock, and Pasture3D adopts it rather than fighting it
#
# Every criterion carries a control that must fail; see the header on each.
#
# Run: Godot_v4.7-stable_win64_console.exe --path project bench/WaterBodiesPhase1Gate.tscn
extends Node

const WATER_DIR := "res://addons/pasture_3d/extras/shaders/water/"
const LAKE_MAT := WATER_DIR + "M_water_lake.tres"
const PROBE_SHADER := "res://bench/water_parity_probe.gdshader"
const DEBUG_SHADER := "res://bench/water_body_debug.gdshader"

const LOOP_PERIOD := 120.0
# Must match PROBE_MAX in water_parity_probe.gdshader.
const PROBES := 64
const CELL_PX := 8
# G4's budget, and the threshold the probe shader's red channel encodes.
const G4_METRES := 0.01

# How far apart criterion B puts its two bodies. Far enough that a shared origin is
# a different phase of the wave field, not a slightly different one.
const B_SEPARATION := 5000.0

var _fail := 0
var _out_dir := ""
var _probe_vp: SubViewport
var _probe_mat: ShaderMaterial
var _last_clock_cell := Color.BLACK


func _ready() -> void:
	var bail := Timer.new()
	bail.wait_time = 600.0
	bail.one_shot = true
	bail.timeout.connect(func():
		push_error("gate timed out")
		get_tree().quit(2))
	add_child(bail)
	bail.start()

	_out_dir = OS.get_environment("BENCH_OUT")
	if _out_dir == "":
		_out_dir = "user://"

	DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)
	Engine.max_fps = 0
	Engine.physics_ticks_per_second = 60
	DisplayServer.window_set_size(Vector2i(1280, 800))

	print("=== Pasture3D Water Bodies — Phase 1 gate ===")
	print("Godot %s | %s | %s" % [
		Engine.get_version_info().string,
		RenderingServer.get_video_adapter_name(),
		RenderingServer.get_current_rendering_method()])
	print("")

	_make_probe_viewport()

	await _gate_a_parity()
	await _gate_b_instance_origin()
	_gate_c_material_cache()
	await _gate_d_clock_ownership()

	print("")
	print("=== PHASE 1 GATE %s ===" % ("PASS" if _fail == 0 else "FAIL (%d)" % _fail))
	get_tree().quit(0 if _fail == 0 else 1)


# ---- A: parity, for two profiles at once --------------------------------------
# G4 for the ocean was proved in the shader work's Phase 4, against one wave table
# generated by one node. What Phase 1 changes is that the table now comes from a
# profile picked by name out of an array, and that several profiles coexist. So the
# question is not "does the Gerstner arithmetic agree" -- that was answered -- it is
# "does profile X's table reach the GPU as profile X's table", which a single-profile
# scene cannot ask at all.
#
# Two profiles, deliberately different in every knob, evaluated in the SAME scene
# from the SAME manager. The probe reads its wave state out of the material the
# manager handed back, so a probe configured differently from the water on screen
# cannot pass.
#
# Two controls. A deliberately wrong CPU array must light red, or "all black" is
# indistinguishable from a probe that never ran -- black being what a pass looks
# like. And the two profiles must disagree with each other: if profile B's probe
# passes against profile A's CPU answers, the manager is handing out one table for
# both names and the criterion is measuring nothing.
func _gate_a_parity() -> void:
	print("[A] CPU/GPU parity for two profiles in one scene:")
	var root := _make_world()
	var manager := _make_manager(root)

	# Freeze the clock before ANY of this. The manager advances water_time every
	# physics frame and writes it to the global, so an unfrozen run computes the CPU
	# answers at one instant and draws the probe at a later one -- which is a real
	# disagreement between two evaluators that are both correct, and reads exactly
	# like a parity failure. The first run of this gate did that and reported 59 of
	# 64 lake probes over G4's 1 cm.
	#
	# `paused` stops the accumulator while the per-frame global write continues, so
	# the shader and the CPU stay pinned to the same number rather than one of them
	# simply stopping.
	for i in 20:
		await get_tree().physics_frame
	manager.paused = true
	await _settle()

	var cases := [
		["lake_calm", 4, 60.0, 0.42, 0.35],
		["pond_still", 2, 18.0, 0.09, 0.20],
	]
	var cpu_by_profile := {}
	var mats := {}

	for case in cases:
		var name: String = case[0]
		var mat: ShaderMaterial = manager.get_material_for(load(LAKE_MAT), name)
		if mat == null:
			_fail += 1
			print("    !! the manager returned no material for '%s'" % name)
			continue
		mats[name] = mat

		var domains := PackedVector2Array()
		var cpu := PackedVector4Array()
		for i in PROBES:
			# Scattered, and nowhere near a multiple of any wavelength in either table.
			var d := Vector2(-900.0 + 31.7 * i, 640.0 - 19.3 * i)
			domains.append(d)
			var p: Vector3 = manager.evaluate_surface_point(name, d)
			cpu.append(Vector4(p.x, p.y, p.z, 0.0))
		cpu_by_profile[name] = cpu

		var lit := await _run_probe(mat, domains, cpu, 0.0, manager.get_water_time())
		print("    %-12s waves=%d  L_max=%.0f  probes over 1 cm: %d | over 1 mm: %d | xz over 1 cm: %d" % [
			name, int(case[1]), float(case[2]), lit.x, lit.y, lit.z])
		# The probe has always computed this cell and nothing was reading it. A
		# clock drift makes every probe fail for a reason that has nothing to do
		# with the wave arithmetic, so it is checked FIRST and reported separately.
		if _last_clock_cell.b > 0.5:
			_fail += 1
			print("    !! the shader's clock is zero; nothing is driving water_time")
		elif _last_clock_cell.r > 0.5:
			_fail += 1
			print("    !! the shader and the CPU are more than 1e-5 s apart, so the two")
			print("       are being asked about different instants and the probe counts")
			print("       below are measuring clock drift, not parity")
		if lit.x > 0:
			_fail += 1
			print("    !! %d of %d probes exceed G4's 1 cm on '%s'" % [lit.x, PROBES, name])

	# Control 1: the CPU answers moved 5 cm. Red must light everywhere.
	if mats.has("lake_calm"):
		var domains := PackedVector2Array()
		var wrong := PackedVector4Array()
		for i in PROBES:
			var d := Vector2(-900.0 + 31.7 * i, 640.0 - 19.3 * i)
			domains.append(d)
			var p: Vector3 = manager.evaluate_surface_point("lake_calm", d)
			wrong.append(Vector4(p.x, p.y + 0.05, p.z, 0.0))
		var lit := await _run_probe(mats["lake_calm"], domains, wrong, 0.0, manager.get_water_time())
		print("    CONTROL, CPU answers offset by 5 cm: %d/%d probes light red (must be %d)" % [
			lit.x, PROBES, PROBES])
		if lit.x != PROBES:
			_fail += 1
			print("    !! the probe does not react to a wrong CPU answer; A is vacuous")

	# Control 2: the two profiles must actually be two profiles. Feed pond's probe
	# the lake's CPU answers; it has to fail.
	if mats.has("pond_still") and cpu_by_profile.has("lake_calm"):
		var domains := PackedVector2Array()
		for i in PROBES:
			domains.append(Vector2(-900.0 + 31.7 * i, 640.0 - 19.3 * i))
		var lit := await _run_probe(mats["pond_still"], domains,
				cpu_by_profile["lake_calm"], 0.0, manager.get_water_time())
		print("    CONTROL, pond's GPU vs lake's CPU: %d/%d probes light red (must be > 0)" % [
			lit.x, PROBES])
		if lit.x == 0:
			_fail += 1
			print("    !! the two profiles produce the same surface, so the manager is")
			print("       handing out one table under two names and A proves nothing")

	root.queue_free()
	await _settle()


# ---- B: the instance uniform --------------------------------------------------
# §5.4's whole argument: ten ponds share one material, but they sit in ten different
# places, and a domain origin stored on the material would force them to share one.
# Promoted to an instance uniform, each body sets its own.
#
# Measured on the SURFACE, not on a readback of the uniform, because "the value I set
# is the value I read" would pass whether or not the shader used it. Two subdivided
# planes, one at the world origin and one 5 km out, each given ITS OWN position as
# its domain origin, drawn with the unlit debug wrapper. Both then evaluate the wave
# field at the same domain coordinates, so their surfaces must be identical.
#
# The control is the bug this replaced: give both instances the SAME origin. The far
# plane is then evaluated 5 km into the wave field and must look different. If it
# does not, the origin is not reaching the shader at all and the criterion is
# comparing two planes that would match no matter what.
func _gate_b_instance_origin() -> void:
	print("")
	print("[B] _water_domain_origin is per instance, not per material:")
	var root := _make_world()
	var manager := _make_manager(root)
	var cam: Camera3D = root.get_node("Camera3D")

	# ONE material, shared. That is the point.
	var shared := ShaderMaterial.new()
	shared.shader = load(DEBUG_SHADER)
	if shared.shader == null:
		_fail += 1
		print("    !! could not load %s; B cannot run" % DEBUG_SHADER)
		root.queue_free()
		return
	var profile: Pasture3DWaveProfile = manager.get_profile("lake_calm")
	shared.set_shader_parameter("_waves", profile.get_shader_table())
	shared.set_shader_parameter("wave_steepness", profile.get_steepness())

	var near := _make_plane(root, Vector3.ZERO, shared)
	var far := _make_plane(root, Vector3(B_SEPARATION, 0.0, 0.0), shared)

	# Freeze so both captures are the same instant.
	manager.paused = true
	_freeze_clock(21.0)

	# Correct: each body's own position is its domain origin.
	near.set_instance_shader_parameter("_water_domain_origin", Vector3.ZERO)
	far.set_instance_shader_parameter("_water_domain_origin", Vector3(B_SEPARATION, 0.0, 0.0))
	cam.position = Vector3(0.0, 12.0, 0.0)
	await _settle()
	var img_near := _grab()
	cam.position = Vector3(B_SEPARATION, 12.0, 0.0)
	await _settle()
	var img_far := _grab()
	var delta_ok := _mean_delta(img_near, img_far)
	_screenshot(_out_dir.path_join("phase1_b_near.png"))

	# The control: both instances told the origin is zero, which is what a material
	# uniform would have forced.
	far.set_instance_shader_parameter("_water_domain_origin", Vector3.ZERO)
	await _settle()
	var img_shared := _grab()
	var delta_bad := _mean_delta(img_near, img_shared)
	_screenshot(_out_dir.path_join("phase1_b_far_shared_origin.png"))

	print("    per-instance origins, near vs far surface: mean delta %.6f" % delta_ok)
	print("    CONTROL, both origins 0 (the material-uniform case): %.6f" % delta_bad)

	# Non-vacuity: the surface must have visible structure at all, or both numbers
	# are zero and the comparison is between two blank images.
	var structure := _spread(img_near)
	print("    surface structure in the near capture (channel spread): %.4f" % structure)
	if structure < 0.05:
		_fail += 1
		print("    !! the debug surface is nearly uniform; B is comparing blank frames")
	elif delta_ok > 0.02:
		_fail += 1
		print("    !! two bodies given their own domain origins do NOT agree; the")
		print("       instance uniform is not reaching the shader")
	elif delta_bad < delta_ok * 4.0:
		_fail += 1
		print("    !! a shared origin looks the same as per-instance origins, so the")
		print("       uniform is being ignored and B proves nothing")
	else:
		print("    -> per-instance agrees (%.6f) and shared does not (%.6f), %.0fx apart" % [
			delta_ok, delta_bad, delta_bad / maxf(delta_ok, 1e-6)])

	manager.paused = false
	root.queue_free()
	await _settle()


# ---- C: the material cache ----------------------------------------------------
# §5.4's promise, stated as a number: ten pools on one profile cost one material and
# one upload. Checked through the API rather than by counting draw calls, because
# the claim is about what the manager builds, and that is what get_cached_material_count
# and get_upload_count report.
#
# Two controls. Ten pools on TEN profiles must produce ten of each, or the counters
# are stuck rather than low. And the cached material must not be the base itself --
# handing back the shipped .tres would also read as "one material", while quietly
# writing the user's wave table into a plugin file.
func _gate_c_material_cache() -> void:
	print("")
	print("[C] the (base material, profile) cache:")
	var root := _make_world()
	var manager := _make_manager(root)
	var base: Material = load(LAKE_MAT)

	var uploads_before: int = manager.get_upload_count()
	var mats := []
	for i in 10:
		mats.append(manager.get_material_for(base, "lake_calm"))
	var uploads := manager.get_upload_count() - uploads_before
	var cached: int = manager.get_cached_material_count()

	var all_same := true
	for m in mats:
		if m != mats[0]:
			all_same = false
	print("    10 pools, one profile -> %d cached material(s), %d upload(s), all identical: %s" % [
		cached, uploads, str(all_same)])
	if cached != 1 or uploads != 1 or not all_same:
		_fail += 1
		print("    !! expected exactly 1 material and 1 upload shared by all ten")

	if mats[0] == base:
		_fail += 1
		print("    !! the cache handed back the BASE material; a plugin preset would be")
		print("       written to, and a plugin update would overwrite the user's water")

	# Control: ten distinct profiles must cost ten of each.
	var profiles: Array[Pasture3DWaveProfile] = []
	for i in 10:
		var p := Pasture3DWaveProfile.new()
		p.profile_name = "ctrl_%d" % i
		p.wave_count = 2 + (i % 6)
		p.length_max = 20.0 + 7.0 * i
		profiles.append(p)
	manager.profiles = profiles
	manager.clear_material_cache()
	var uploads2_before: int = manager.get_upload_count()
	for i in 10:
		manager.get_material_for(base, "ctrl_%d" % i)
	var uploads2 := manager.get_upload_count() - uploads2_before
	print("    CONTROL, 10 pools on 10 profiles -> %d cached, %d uploads (must be 10/10)" % [
		manager.get_cached_material_count(), uploads2])
	if manager.get_cached_material_count() != 10 or uploads2 != 10:
		_fail += 1
		print("    !! the counters do not move with distinct profiles, so the '1 and 1'")
		print("       above is a stuck counter and not a cache hit")

	root.queue_free()


# ---- D: who owns the clock ----------------------------------------------------
# Two nodes writing water_time from their own accumulators leaves the global
# carrying whichever wrote last. Worse, Pasture3D's CPU query reads its OWN
# _water_time while the surface is drawn from the global, so a scene with both a
# terrain and a manager would break G4 for a reason invisible in either file.
#
# Pasture3D therefore adopts the manager's clock. Checked as an equality between the
# two nodes' reported times after the same physics, with a control that removes the
# manager and requires the terrain to resume driving its own clock -- otherwise
# "they agree" would also be what two stopped clocks look like.
func _gate_d_clock_ownership() -> void:
	print("")
	print("[D] Pool3DManager owns the clock; Pasture3D adopts it:")
	var root := _make_world()
	var manager := _make_manager(root)
	# A deliberately different period, so the two clocks cannot agree by accident.
	manager.loop_period = 37.0
	var terrain := Pasture3D.new()
	terrain.ocean_material = load(WATER_DIR + "M_water_ocean.tres")
	terrain.ocean_enabled = true
	terrain.ocean_wave_loop_period = LOOP_PERIOD
	terrain.render_layers = 1 << 4
	root.add_child(terrain)

	for i in 90:
		await get_tree().physics_frame
	await _settle()

	var t_manager: float = manager.get_water_time()
	var t_terrain: float = terrain.get_water_time()
	print("    manager %.6f | terrain %.6f | difference %.9f" % [
		t_manager, t_terrain, absf(t_manager - t_terrain)])
	if t_manager <= 0.0:
		_fail += 1
		print("    !! the manager's clock never advanced; D is vacuous")
	elif absf(t_manager - t_terrain) > 1e-5:
		_fail += 1
		print("    !! the terrain is running its own clock while a manager is present;")
		print("       the CPU query and the drawn surface are on different instants")
	else:
		print("    -> the terrain adopted the manager's clock")

	# Control: remove the manager. The terrain must resume driving, or the agreement
	# above is two nodes that both stopped rather than one deferring to the other.
	var before: float = terrain.get_water_time()
	root.remove_child(manager)
	manager.queue_free()
	for i in 30:
		await get_tree().physics_frame
	await _settle()
	var after: float = terrain.get_water_time()
	print("    CONTROL, manager removed: terrain clock %.6f -> %.6f (must advance)" % [
		before, after])
	if absf(after - before) < 1e-4:
		_fail += 1
		print("    !! the terrain does not resume its own clock, so it was not deferring")
		print("       to the manager -- it had simply stopped")

	root.queue_free()
	await _settle()


# ---- helpers ------------------------------------------------------------------
func _make_world() -> Node3D:
	var root := Node3D.new()
	add_child(root)
	var env := Environment.new()
	var sky := Sky.new()
	sky.sky_material = ProceduralSkyMaterial.new()
	env.background_mode = Environment.BG_SKY
	env.sky = sky
	env.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	env.reflected_light_source = Environment.REFLECTION_SOURCE_SKY
	var we := WorldEnvironment.new()
	we.environment = env
	root.add_child(we)
	var sun := DirectionalLight3D.new()
	sun.name = "Sun"
	sun.rotation_degrees = Vector3(-38, 130, 0)
	sun.shadow_enabled = false
	root.add_child(sun)
	var cam := Camera3D.new()
	cam.name = "Camera3D"
	cam.position = Vector3(0, 12, 0)
	cam.rotation_degrees = Vector3(-25, 0, 0)
	cam.far = 20000.0
	cam.cull_mask = 1
	cam.current = true
	root.add_child(cam)
	return root


func _make_manager(p_root: Node3D) -> Pool3DManager:
	var manager := Pool3DManager.new()
	manager.name = "Pool3DManager"
	manager.loop_period = LOOP_PERIOD

	var lake := Pasture3DWaveProfile.new()
	lake.profile_name = "lake_calm"
	lake.wave_count = 4
	lake.direction_deg = 0.0
	lake.spread_deg = 36.0
	lake.amplitude = 0.42
	lake.length_max = 60.0
	lake.steepness = 0.35

	var pond := Pasture3DWaveProfile.new()
	pond.profile_name = "pond_still"
	pond.wave_count = 2
	pond.direction_deg = 20.0
	pond.spread_deg = 50.0
	pond.amplitude = 0.09
	pond.length_max = 18.0
	pond.steepness = 0.20

	var profiles: Array[Pasture3DWaveProfile] = [lake, pond]
	manager.profiles = profiles
	p_root.add_child(manager)
	manager.sun_light = p_root.get_node("Sun")
	return manager


# A plane dense enough that the waves are visible at all: they are a VERTEX effect,
# and a two-triangle plane cannot show one.
func _make_plane(p_root: Node3D, p_pos: Vector3, p_mat: Material) -> MeshInstance3D:
	var mesh := PlaneMesh.new()
	mesh.size = Vector2(200.0, 200.0)
	mesh.subdivide_width = 120
	mesh.subdivide_depth = 120
	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.material_override = p_mat
	mi.position = p_pos
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	mi.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	p_root.add_child(mi)
	return mi


func _make_probe_viewport() -> void:
	_probe_mat = ShaderMaterial.new()
	_probe_mat.shader = load(PROBE_SHADER)
	_probe_vp = SubViewport.new()
	# One cell wider than PROBES: the last one is the clock cell.
	_probe_vp.size = Vector2i((PROBES + 1) * CELL_PX, 16)
	_probe_vp.disable_3d = true
	_probe_vp.transparent_bg = false
	_probe_vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	var rect := ColorRect.new()
	rect.size = _probe_vp.size
	rect.material = _probe_mat
	_probe_vp.add_child(rect)
	add_child(_probe_vp)


func _run_probe(p_source: ShaderMaterial, p_domains: PackedVector2Array,
		p_cpu: PackedVector4Array, p_base_y: float, p_cpu_time: float) -> Vector3i:
	var packed := PackedVector4Array()
	for d in p_domains:
		packed.append(Vector4(d.x, d.y, 0.0, 0.0))

	# Read the wave state off the material the MANAGER handed out, so a probe
	# configured differently from the water on screen cannot pass.
	_probe_mat.set_shader_parameter("_waves", p_source.get_shader_parameter("_waves"))
	_probe_mat.set_shader_parameter("wave_steepness",
			p_source.get_shader_parameter("wave_steepness"))
	# The probe declares this as a plain uniform (WATER_PLAIN_DOMAIN_ORIGIN); the
	# bodies' origin is per instance and is criterion B's business, not A's.
	_probe_mat.set_shader_parameter("_water_domain_origin", Vector3.ZERO)
	_probe_mat.set_shader_parameter("probe_in", packed)
	_probe_mat.set_shader_parameter("probe_cpu", p_cpu)
	_probe_mat.set_shader_parameter("probe_count", p_domains.size())
	_probe_mat.set_shader_parameter("cell_px", float(CELL_PX))
	_probe_mat.set_shader_parameter("base_y", p_base_y)
	_probe_mat.set_shader_parameter("cpu_time", p_cpu_time)

	await _settle()
	var img := _probe_vp.get_texture().get_image()
	var lit := Vector3i.ZERO
	var y := img.get_height() / 2
	_last_clock_cell = img.get_pixel(p_domains.size() * CELL_PX + CELL_PX / 2, y)
	for i in p_domains.size():
		var c := img.get_pixel(i * CELL_PX + CELL_PX / 2, y)
		if c.r > 0.5:
			lit.x += 1
		if c.g > 0.5:
			lit.y += 1
		if c.b > 0.5:
			lit.z += 1
	return lit


func _freeze_clock(p_time: float) -> void:
	RenderingServer.global_shader_parameter_set("water_time", p_time)
	RenderingServer.global_shader_parameter_set("water_time_period", LOOP_PERIOD)


func _settle() -> void:
	for i in 10:
		await RenderingServer.frame_post_draw


func _grab() -> Image:
	return get_viewport().get_texture().get_image()


func _screenshot(p_path: String) -> void:
	var err := _grab().save_png(p_path)
	if err != OK:
		_fail += 1
		push_error("could not write %s (error %d)" % [p_path, err])


func _mean_delta(p_a: Image, p_b: Image) -> float:
	var total := 0.0
	var n := 0
	for y in range(0, p_a.get_height(), 4):
		for x in range(0, p_a.get_width(), 4):
			var ca := p_a.get_pixel(x, y)
			var cb := p_b.get_pixel(x, y)
			total += (absf(ca.r - cb.r) + absf(ca.g - cb.g) + absf(ca.b - cb.b)) / 3.0
			n += 1
	return total / float(maxi(n, 1))


# Max-minus-min of the green channel over the frame. Cheap "is there anything here"
# check: a blank or uniform image scores ~0, and two blank images mean-delta to 0
# against each other, which would read as a pass.
func _spread(p_img: Image) -> float:
	var lo := 1.0
	var hi := 0.0
	for y in range(0, p_img.get_height(), 4):
		for x in range(0, p_img.get_width(), 4):
			var g := p_img.get_pixel(x, y).g
			lo = minf(lo, g)
			hi = maxf(hi, g)
	return hi - lo
