name: Upload Artifact
description: Uploads built package
runs:
  using: "composite"
  steps:
    - name: Upload Package, 1st attempt
      id: upload1
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/project/

    - name: Upload Package, 2nd attempt
      id: upload2
      if: steps.upload1.outcome == 'failure'
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/project/

    - name: Upload Package, 3rd attempt
      id: upload3
      if: steps.upload1.outcome == 'failure' && steps.upload2.outcome == 'failure'
      uses: actions/upload-artifact@v3
      with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/project/
