name: 🌐 Web Builds
on: [ workflow_call, workflow_dispatch ]

jobs:
  build:
    name: 🌐 Web ${{ matrix.arch }} ${{ matrix.target }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [web]
        target: [debug, release]
        #threads: [yes, no]

    steps:
      - name: Checkout Terrain3D
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Base Dependencies
        uses: ./.github/actions/base-deps
        with:
          platform: ${{ matrix.platform }}

      - name: Setup Build Cache
        uses: ./.github/actions/build-cache
        with:
          cache-name: ${{ matrix.platform }}-nothreads-${{ matrix.target }}
        continue-on-error: true

      - name: Build Terrain3D
        env:
            SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
            TARGET: 'template_${{ matrix.target }}'
        shell: sh
        run: |
          scons target=$TARGET platform='${{ matrix.platform }}' threads=no debug_symbols=no -j2

      - name: Prepare Files
        shell: sh
        run: |
          ls -l project/addons/terrain_3d/bin/
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.txt' ${{ github.workspace }}/project/addons/terrain_3d/

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: t3d-${{ matrix.platform }}-nothreads-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/project/
  
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          include-hidden-files: true
          name: ${{ github.event.repository.name }}
          pattern: t3d-*
          delete-merged: true