name: 🪟 Windows Builds
on: [ workflow_call, workflow_dispatch ]

jobs:
  build:
    name: 🪟 Windows ${{ matrix.arch }} ${{ matrix.target }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [windows]
        target: [debug, release]
        arch: [x86_64]

    steps:
      - name: Checkout Terrain3D
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Windows Dependencies
        uses: ./.github/actions/windows-deps

      - name: Setup Base Dependencies
        uses: ./.github/actions/base-deps

      - name: Setup Build Cache
        uses: ./.github/actions/build-cache
        with:
          cache-name: ${{ matrix.platform }}-${{ matrix.target }}
        continue-on-error: true

      - name: Build Terrain3D
        env:
            SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
            TARGET: 'template_${{ matrix.target }}'
            ARCH: '${{ matrix.arch }}'
        shell: sh
        run: |
            scons target=$TARGET platform='${{ matrix.platform }}' arch=$ARCH debug_symbols=no -j2

      - name: Prepare Files
        shell: sh
        run: |
          ls -l project/addons/terrain_3d/bin/
          strip project/addons/terrain_3d/bin/libterrain.*
          ls -l project/addons/terrain_3d/bin/
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.txt' ${{ github.workspace }}/project/addons/terrain_3d/

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: t3d-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/project/

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ github.event.repository.name }}
          pattern: t3d-*
          delete-merged: true