name: 🪟 Windows Builds
on: [ workflow_call, workflow_dispatch ]

jobs:
  build:
    name: 🪟 Windows ${{ matrix.config.arch }} ${{ matrix.target }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        target: [debug, release]
        config:
          - arch: x86_64
            platform: windows
            flags: ""
          - arch: arm64
            platform: windows
            flags: use_mingw=yes use_llvm=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: ./.github/actions/build-artifact
        with:
          cache-name: ${{ matrix.config.platform }}-${{ matrix.config.arch }}-${{ matrix.target }}
          platform: ${{ matrix.config.platform }}
          arch: ${{ matrix.config.arch }}
          target: ${{ matrix.target }}
          flags: ${{ matrix.config.flags }}
